# Generated by Django 5.0.3 on 2024-09-10 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0002_rename_admins_admin_rename_events_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='officer',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
