# Generated by Django 5.0.3 on 2024-09-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0004_rename_incidents_evidence_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='date_joined',
            new_name='date_reported',
        ),
    ]
