# Generated by Django 5.0.3 on 2024-09-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0005_rename_date_joined_incidentreport_date_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
