# Generated by Django 5.1.1 on 2024-09-29 07:48

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='file_path',
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[pangolin.models.validate_file_type]),
        ),
    ]
