# Generated by Django 5.1.1 on 2024-09-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0007_remove_evidence_file_path_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=150),
        ),
    ]
