# Generated by Django 5.1.1 on 2024-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0009_alter_incident_city_alter_incident_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='city',
            field=models.CharField(blank=True, choices=[('Puerto Princesa City', 'Puerto Princesa City')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='municipality',
            field=models.CharField(blank=True, choices=[('Aborlan', 'Aborlan'), ('Agutaya', 'Agutaya'), ('Araceli', 'Araceli'), ('Balabac', 'Balabac'), ('Bataraza', 'Bataraza'), ("Brooke's Point", "Brooke's Point"), ('Busuanga', 'Busuanga'), ('Cagayancillo', 'Cagayancillo'), ('Coron', 'Coron'), ('Culion', 'Culion'), ('Cuyo', 'Cuyo'), ('Dumaran', 'Dumaran'), ('El Nido', 'El Nido'), ('Kalayaan', 'Kalayaan'), ('Linapacan', 'Linapacan'), ('Magsaysay', 'Magsaysay'), ('Narra', 'Narra'), ('Puerto Princesa', 'Puerto Princesa'), ('Quezon', 'Quezon'), ('Rizal', 'Rizal'), ('Roxas', 'Roxas'), ('San Vicente', 'San Vicente'), ('Sofronio Española', 'Sofronio Española'), ('Taytay', 'Taytay')], max_length=150, null=True),
        ),
    ]
