# Generated by Django 5.1.1 on 2024-10-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0010_alter_incident_city_alter_incident_municipality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='officer',
            new_name='officers',
        ),
    ]
