# Generated by Django 5.1.1 on 2024-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0011_rename_officer_event_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='officer_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
