# Generated by Django 5.1.1 on 2024-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0012_officer_officer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.CharField(max_length=150)),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
