# Generated by Django 5.1.1 on 2024-10-18 08:32

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0013_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery/', validators=[pangolin.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='officer',
            name='officer_image',
            field=models.ImageField(blank=True, null=True, upload_to='officers/'),
        ),
    ]
