# Generated by Django 5.1.1 on 2024-10-18 09:00

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0014_alter_gallery_image_alter_officer_officer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(null=True, upload_to='gallery/', validators=[pangolin.models.validate_file_type]),
        ),
    ]
