# Generated by Django 5.1.1 on 2024-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0016_rename_image_gallery_media_alter_gallery_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='fb_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='ig_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
