# Generated by Django 5.1.1 on 2024-10-21 15:52

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0019_alter_user_contact_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(validators=[pangolin.models.validate_contact]),
        ),
    ]
