# Generated by Django 5.1.1 on 2024-11-07 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0022_alter_officer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
