# Generated by Django 5.1.3 on 2024-11-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0024_remove_incident_city_remove_incident_municipality_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='user_firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='user_lastname',
        ),
    ]
