# Generated by Django 5.1.3 on 2024-11-20 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0027_incidentreport_feces_incidentreport_life_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='feces',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='life_history',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='obl_rolled',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='obl_stretched',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='ticks',
        ),
        migrations.AddField(
            model_name='incident',
            name='feces',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='life_history',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='obl_rolled',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='obl_stretched',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='ticks',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='municity',
            field=models.CharField(choices=[('Aborlan', 'Aborlan'), ('Agutaya', 'Agutaya'), ('Araceli', 'Araceli'), ('Balabac', 'Balabac'), ('Bataraza', 'Bataraza'), ("Brooke's Point", "Brooke's Point"), ('Busuanga', 'Busuanga'), ('Cagayancillo', 'Cagayancillo'), ('Coron', 'Coron'), ('Culion', 'Culion'), ('Cuyo', 'Cuyo'), ('Dumaran', 'Dumaran'), ('El Nido', 'El Nido'), ('Kalayaan', 'Kalayaan'), ('Linapacan', 'Linapacan'), ('Magsaysay', 'Magsaysay'), ('Narra', 'Narra'), ('Puerto Princesa City', 'Puerto Princesa City'), ('Quezon', 'Quezon'), ('Rizal', 'Rizal'), ('Roxas', 'Roxas'), ('San Vicente', 'San Vicente'), ('Sofronio Española', 'Sofronio Española'), ('Taytay', 'Taytay')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
