# Generated by Django 5.1.3 on 2024-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0030_incident_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
