# Generated by Django 5.1.3 on 2024-11-26 13:18

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0032_officer_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[pangolin.models.validate_contact]),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidences/', validators=[pangolin.models.validate_file_type]),
        ),
    ]
