# Generated by Django 5.1.3 on 2024-11-26 13:28

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0033_incidentreport_contact_incidentreport_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='evidence',
            field=models.FileField(blank=True, default=None, null=True, upload_to='evidences/', validators=[pangolin.models.validate_file_type]),
        ),
    ]
