# Generated by Django 5.1.3 on 2024-11-26 14:39

import pangolin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0034_alter_incidentreport_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidences/', validators=[pangolin.models.validate_file_type]),
        ),
    ]
