# Generated by Django 5.1.3 on 2024-11-27 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pangolin', '0035_alter_incidentreport_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
